### ISSUE TITLE
Support shanghai fork

### ISSUE THREAD

**Issue by silathdiir** [scroll-tech/zkevm-circuits#504]
### Tasks for shanghai-fork

- [x] add feature shanghai and change tracer accordingly https://github.com/scroll-tech/zkevm-circuits/pull/497
- [x] EIP-3651: Warm COINBASE https://github.com/scroll-tech/zkevm-circuits/pull/500
- [x] EIP-3860: Limit and meter initcode https://github.com/scroll-tech/zkevm-circuits/pull/507
- [x] EIP-3855: PUSH0 instruction https://github.com/scroll-tech/zkevm-circuits/pull/510
- [x] upgrade testool/tests submodule commit and re-run testool https://github.com/scroll-tech/zkevm-circuits/pull/511
- [ ] EIP-4895: Beacon Chain push withdrawals
- [ ] EIP-6049: Deprecate SELFDESTRUCT - may also add `shanghai` feature to `SELFDESTRUCT` as https://github.com/scroll-tech/zkevm-circuits/pull/463
