### ISSUE TITLE
Tracking issue for "Invalid Inputs" to Precompiled Contract Calls

### ISSUE THREAD

**Issue by roynalnaruto** [scroll-tech/zkevm-circuits#799]
### Describe the feature you would like

At the moment (as of commit: https://github.com/scroll-tech/zkevm-circuits/commit/d3ffb462e0af7f331fa836f1b893d6e6e4d10642) we are bypassing errors in precompiled contract calls, i.e. `call.is_success == false` by redirecting them to [`ErrorPrecompileFailedGadget`](https://github.com/scroll-tech/zkevm-circuits/blob/d3ffb462e0af7f331fa836f1b893d6e6e4d10642/zkevm-circuits/src/evm_circuit/execution/error_precompile_failed.rs).

Ideally, each precompile's gadget should handle and validate errors encountered to calls made to that respective precompiled contract. Below listed are the various failure cases encountered by precompiled calls, and must be handled by the respective gadget.

- [ ] [`Ecrecover`](https://github.com/scroll-tech/zkevm-circuits/blob/d3ffb462e0af7f331fa836f1b893d6e6e4d10642/zkevm-circuits/src/evm_circuit/execution/precompiles/ecrecover.rs)
    + Insufficient Gas
- [ ] [`Identity`](https://github.com/scroll-tech/zkevm-circuits/blob/d3ffb462e0af7f331fa836f1b893d6e6e4d10642/zkevm-circuits/src/evm_circuit/execution/precompiles/identity.rs)
    + Insufficient Gas
- [x] [`EcAdd`](https://github.com/scroll-tech/zkevm-circuits/blob/d3ffb462e0af7f331fa836f1b893d6e6e4d10642/zkevm-circuits/src/evm_circuit/execution/precompiles/ec_add.rs)
    + `P_x` is not in `Fq`
    + `P_y` is not in `Fq`
    + `P` is not on curve `G1`
    + `Q_x` is not in `Fq`
    + `Q_y` is not in `Fq`
    + `Q` is not on curve `G1`
    + Insufficient Gas
- [x] [`EcMul`](https://github.com/scroll-tech/zkevm-circuits/blob/d3ffb462e0af7f331fa836f1b893d6e6e4d10642/zkevm-circuits/src/evm_circuit/execution/precompiles/ec_mul.rs)
    + `P_x` is not in `Fq`
    + `P_y` is not in `Fq`
    + `P` is not on curve `G1`
    + Insufficient Gas
- [x] [`EcPairing`](https://github.com/scroll-tech/zkevm-circuits/blob/d3ffb462e0af7f331fa836f1b893d6e6e4d10642/zkevm-circuits/src/evm_circuit/execution/precompiles/ec_pairing.rs).
    + `len(input) % 192 != 0`
    + `len(input) > 768`
    + `A_x` is not in `Fq`
    + `A_y` is not in `Fq`
    + `A` is not on curve `G1`
    + `B_x0` is not in `Fq`
    + `B_x1` is not in `Fq`
    + `B_y0` is not in `Fq`
    + `B_y1` is not in `Fq`
    + `B` is not on curve `G2`
    + Insufficient Gas
- [ ] [`Modexp`](https://github.com/scroll-tech/zkevm-circuits/blob/d3ffb462e0af7f331fa836f1b893d6e6e4d10642/zkevm-circuits/src/evm_circuit/execution/precompiles/modexp.rs)
    + `Base` length overflow
    + `Modulus` length overflow
    + `Exponent` length overflow
    + Insufficient Gas

The cases for `Insufficient Gas` are being worked in the PR: #815
